feat(MainClient): add new methods
idezdigital/laravel-caradhras-sdk pull request #15
Opened 2022-11-25 17:05 UTC by davi0kaipper

- findIndividual
- associateCardToAccount
- updateIndividuals

adds to the package classes that are used by those methods

2022-12-13 21:39 UTC, davi0kaipper commented
wip

2022-12-27 20:57 UTC, pedro-santiago commented on src/Clients/CaradhrasMainClient.php
> +        $status = AccountStatus::Canceled;
Esse account status precisa ser o da dock, não o nosso.

2023-01-03 20:41 UTC, arthurtavaresdev requested changes
Algumas mudanças pontuais, mas bom trabalho

2023-01-03 20:41 UTC, arthurtavaresdev commented on database/factories/CardSettingsFactory.php
> +            'numeroCartaoHash' => -6892947191434469588,
Isso aqui é negativo mesmo?

2023-01-03 20:41 UTC, arthurtavaresdev commented on database/factories/CardMccGroupControlFactory.php
> +                "intervaloMatch" => 5,
Esses dados poderiam ser aleatorizados

2023-01-03 20:41 UTC, arthurtavaresdev commented on database/factories/CardSettingsFactory.php
> +            'arquivoImpressao' => 'IDEZ_2PJ_130520',
Dados poderiam ser aleatorizados.

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Clients/CaradhrasMainClient.php
> +            $message = $response->status() === 404 ? 'Failed to get individual.' : 'Individual not found.';
Aqui não está ao Contrário?

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Clients/CaradhrasMainClient.php
> +            throw new CaradhrasException($message, $statusCode);
Poderia ser algo como veja na API o `ApprovalException`
```suggestion
            throw new CaradhrasException::failedGetIndividual()
            
            // or 
            
            throw new CaradhrasException::IndividualNotFound()
```

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Clients/CaradhrasMainClient.php
> +            throw new CaradhrasException('Individual not found.', 404);
```suggestion
            throw new CaradhrasException::IndividualNotFound()
```

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Clients/CaradhrasMainClient.php
> +            ->first();
```suggestion
            ->firstWhere(fn ($individual) => $individual?->idRegistration === $registrationId)
```

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Clients/CaradhrasMainClient.php
> +    public function associateCardToAccount(int $cardId, int $accountId, int $individualId): bool
Mas seria bom colocar o nome `Prepago` na chamada dessa função

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Clients/CaradhrasMainClient.php
> +            ->throw();
Faz sentido retornar um `throw`? Não deveria ser um `false`

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Contracts/NovaSelectEnumInterface.php
> +    public static function novaOptions(): array;
Como trata-se de um pacote, acredito que ele deva ser mais abstrato. Mas estou aberto a discussão

```suggestion
interface SelectEnumInterface
{
    public function label(): string;

    public static function options(): array;
```

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Data/AccountStatus.php
> +            self::Failed => 'Falha na Criação',
```suggestion
            self::Failed => 'Falhou',
```

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Data/AccountStatus.php
> +    case WaitingAnalysis = 'waiting_analysis';
Esse Status são nossos, não do Caradhras. Logo isso deve ficar na API

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Data/AccountStatusCode.php
> +enum AccountStatusCode: int
Esse é o Status que deve permanercer

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Data/Card.php
> +    }
BOA

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Data/ConciergePayload.php
> + * @property string|null $createdAt
Cria esses dois parametros, caso contrário no PHP 8.2 irá pará de funcionar.

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Data/Struct.php
> +            if (is_object($var) && enum_exists($var::class)) {
```suggestion
            if ($var instanceof \BackendEnum) {
```

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Data/Struct.php
> +
if ($value instanceof self) {
                $value = $value->toArray();
            }

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Data/TransactionOperation.php
> +enum TransactionOperation: string implements NovaSelectEnumInterface
Isso tambem pode deixar na API

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Data/TransactionOperation.php
> +            'Remuneração-Cta Pgto' => self::DailyIncome,
Cria uma outra enum para esses Descriptions

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Exceptions/BaseException.php
> +    public const DEFAULT_ERROR_KEY = 'api.generic_error';
```suggestion
    public const DEFAULT_ERROR_KEY = 'caradhras.generic_error';
```

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Exceptions/BaseException.php
> +        $this->message = $message ?? trans('errors.api.generic_error');
Trouxemos esse translate?

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Exceptions/FailedCreatePersonalAccount.php
> +    public const BLACK_LIST_DOCUMENT = 'black_list_document';
Poderia ser uma Enum?

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Exceptions/FailedCreatePersonalAccount.php
> +        $errorKey = 'caradhras.account.something_went_wrong';
Erro keys tambem poderia ser mapeadas num Enum ou até uma const.

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Exceptions/FailedCreatePersonalAccount.php
> +        }
Não vou mentir que esse código ta feio.

Use Early return aqui.

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Exceptions/FailedCreatePersonalAccount.php
> +        }
Poderia ser duas funções estasticas diferentes sendo chamadas em diferentes momentos, me parece errado ter regra de negocio no Exception

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Exceptions/FailedCreatePersonalAccount.php
> +class FailedCreatePersonalAccount extends BaseException
```suggestion
class FailedCreatePersonalAccount extends BaseException implements ExceptionLevel
```

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Exceptions/FraudDetectorException.php
> +            trans('errors.fraud_detection'),
Essa tradução consta no pacote?

2023-01-03 20:41 UTC, arthurtavaresdev commented on src/Traits/NovaSelectEnum.php
> +trait NovaSelectEnum
Duvidas se é necessário existir isso aqui

2023-01-04 23:46 UTC, davi0kaipper commented on src/Exceptions/FailedCreatePersonalAccount.php
> +        $errorKey = 'caradhras.account.something_went_wrong';
não é cabível também usar o arquivo de erros do caradhras mesmo?

2023-01-05 01:37 UTC, davi0kaipper commented
wip

2023-01-06 16:54 UTC, davi0kaipper commented on database/factories/CardSettingsFactory.php
> +            'numeroCartaoHash' => -6892947191434469588,
pelo que entendi hashs podem ser negativas também

2023-01-06 20:09 UTC, arthurtavaresdev requested changes
O método src/Clients/CaradhrasMainClient.php tem responsabilidade demais

2023-01-06 20:09 UTC, arthurtavaresdev commented on lang/en/transactions.php
> +    TransactionOperation::RefundTransferReceived->value => 'Transfer Refund Received',
Filtre apenas as traduções necessárias para o pacote.

2023-01-06 20:09 UTC, arthurtavaresdev commented on src/Clients/CaradhrasMainClient.php
> +            ->throw();
Depende do erro... Pensando sobre

2023-01-06 20:09 UTC, arthurtavaresdev commented on src/Clients/CaradhrasMainClient.php
> +            throw new CaradhrasException(trans("errors.services.{$errorKey}"), 502, $errorKey);
Necessário essa interpolação? ficou meio feio

2023-01-06 20:09 UTC, arthurtavaresdev commented on src/Clients/CaradhrasMainClient.php
> +
Não deveria ter um client de Cards?

2023-01-06 20:09 UTC, arthurtavaresdev commented on src/Clients/CaradhrasMainClient.php
> +    }
Tem varias rotas relacionado a Individuals, não poderiamos criar um Client pra isso?

2023-01-06 20:09 UTC, arthurtavaresdev commented on src/Clients/CaradhrasMainClient.php
> +    }
CardClient

2023-01-06 20:09 UTC, arthurtavaresdev commented on src/Clients/CaradhrasMainClient.php
> +
CardClient

2023-01-06 20:09 UTC, arthurtavaresdev commented on src/Clients/CaradhrasMainClient.php
> +
IndividualClient

2023-01-06 20:09 UTC, arthurtavaresdev commented on src/Enums/Transaction/TransactionOperation.php
> +enum TransactionOperation: string implements NovaSelectEnumInterface
Tenho a impressão que isso deveria estar na API

2023-01-06 21:00 UTC, davi0kaipper commented on database/factories/CardMccGroupControlFactory.php
> +                "intervaloMatch" => 5,
da serie de coisas que supostamente alterei e pushei mas não subiram pro origin

2023-01-06 21:15 UTC, davi0kaipper commented on src/Enums/Transaction/TransactionOperation.php
> +enum TransactionOperation: string implements NovaSelectEnumInterface
a factory de transaction usa

2023-01-06 21:21 UTC, davi0kaipper commented on src/Clients/CaradhrasMainClient.php
> +            throw new CaradhrasException(trans("errors.services.{$errorKey}"), 502, $errorKey);
no caso a interpolação seria atribuir ao error key? melhor seria hardcoded?

2023-01-06 21:36 UTC, davi0kaipper commented on lang/en/caradhras.php
> +        'default' => "There was an instability in the provider, please try again later.",
justo

2023-01-06 21:40 UTC, davi0kaipper commented on src/Exceptions/FailedCreatePersonalAccount.php
> +        return ['errorKey' => '', 'message' => ''];
a ideia é de que se não passar a condição do if, fica vazio. e a próxima função vai preencher o valor caso esteja vazio. esse refactor que te comentei ter me confundido

2023-01-06 21:42 UTC, davi0kaipper commented on database/factories/CardMccGroupControlFactory.php
> +                "intervaloMatch" => 5,
![image](https://user-images.githubusercontent.com/107968269/211104829-a8f94598-b322-46b0-b773-af4a81eb9618.png)

"duracao" => $this->faker->numberBetween(1, 59),
"percentualMin" => $this->faker->randomFloat(2, 1, 90),
"percentualMax" => $this->faker->randomFloat(2, 1, 90),
"intervaloMatch" => $this->faker->numberBetween(1, 9),

2023-01-06 21:44 UTC, davi0kaipper commented on database/factories/CardMccGroupControlFactory.php
> +                "intervaloMatch" => 5,
se tiver ok tu só sugere essa correção aqui pf que eu consigo commitar daqui mesmo. caso tenha alguma outra sugestão blz tbm

2023-01-06 21:50 UTC, davi0kaipper commented on lang/en/transactions.php
> +    TransactionOperation::RefundTransferReceived->value => 'Transfer Refund Received',
assumindo que as traduções são usadas no api, a classe desse enum, por conta do método label, iria depender de uma classe externa

2023-01-06 22:00 UTC, davi0kaipper commented
deixei algumas respostas e marquei como resolved conversation. to pensando agora, é o correto eu marcar assim quando eu responder a questão ou só quando realmente terminarmos aquela discussão? quanto aos teus comentários sobre criar outros clients, acho pode servir bem, mas penso sobre a granularidade necessária de divisão em clients. já tem uma boa quantidade. o que acha, @pedro-santiago?

2023-01-10 19:15 UTC, arthurtavaresdev requested changes
Boa, estamos quase lá

2023-01-10 19:15 UTC, arthurtavaresdev commented on src/Clients/CaradhrasCardClient.php
> +            'dataValidade' => now()->addYears(5)->toDateString() . 'T00:00:00.000',
Poderiamos passar isso aqui por Parametro, e esse formato de data tem um formatação no Carbon que já faz isso.

```suggestion
            'dataValidade' => now()->addYears(5)->format('Y-m-d\TH:i:s')
```

2023-01-10 19:15 UTC, arthurtavaresdev commented on src/Clients/CaradhrasCardClient.php
> +        $this->setCardPassword($cardId, random_int(1000, 9999));
Pensando se deveriamos gerar essa senha aleatoria aqui.

2023-01-10 19:15 UTC, arthurtavaresdev commented on src/Enums/Transaction/TransactionOperation.php
> +    }
Podemos remover isso aqui

2023-01-10 19:15 UTC, arthurtavaresdev commented on src/Enums/Transaction/TransactionOperation.php
> +    use NovaSelectEnum;
Não é necessária esta ENUM

2023-01-10 19:15 UTC, arthurtavaresdev commented on src/Clients/CaradhrasCardClient.php
> +                403 => trans(self::CARD_NOT_PRINTED),
É realmente necessário uma const pra isso?

Nao poderiamos chamar diretamente a tradução?

2023-01-10 19:21 UTC, davi0kaipper commented on src/Clients/CaradhrasCardClient.php
> +        $this->setCardPassword($cardId, random_int(1000, 9999));
no caso tu ta questionando o lugar ou o ato de gerar a senha aleatória?

2023-01-10 19:27 UTC, davi0kaipper commented on src/Clients/CaradhrasCardClient.php
> +                403 => trans(self::CARD_NOT_PRINTED),
poderiamos sim. fico com receio de hardcodar

2023-01-10 19:36 UTC, davi0kaipper commented on src/Exceptions/BaseException.php
> +        $this->message = $message ?? 'Ocorreu um erro ao realizar a requisição.';
vai ser traduzida nessa mesma declaração de $this->message, mas vou trocar

2023-01-10 19:43 UTC, davi0kaipper commented on src/Clients/CaradhrasCardClient.php
> +            'dataValidade' => now()->addYears(5)->toDateString() . 'T00:00:00.000',
isso o que?

2023-01-10 19:57 UTC, arthurtavaresdev commented on src/Clients/CaradhrasCardClient.php
> +            'dataValidade' => now()->addYears(5)->toDateString() . 'T00:00:00.000',
a formtação da data.

2023-01-10 19:57 UTC, arthurtavaresdev commented on src/Clients/CaradhrasCardClient.php
> +        $this->setCardPassword($cardId, random_int(1000, 9999));
O Ato

2023-01-10 20:00 UTC, arthurtavaresdev requested changes

2023-01-10 20:00 UTC, arthurtavaresdev commented on src/Clients/CaradhrasCardClient.php
> +    public const CARD_NOT_PRINTED = 'Invalid card status for activation.';
Esta CONST está sendo utizada?

2023-01-12 12:13 UTC, davi0kaipper commented on src/Clients/CaradhrasCardClient.php
> +                403 => 'Status de cartão inválido para ativação.',
tá lá no PT-br/errors

2023-01-12 12:15 UTC, davi0kaipper commented on src/Clients/CaradhrasCardClient.php
> +    public const CARD_NOT_PRINTED = 'Invalid card status for activation.';
nao

2023-01-12 13:34 UTC, arthurtavaresdev commented on src/Clients/CaradhrasCardClient.php
> +                403 => 'Status de cartão inválido para ativação.',
Esse 403 pode utilizar um trans()

2023-01-12 13:44 UTC, arthurtavaresdev requested changes
tamo quaaaaaaaaase

2023-01-12 13:44 UTC, arthurtavaresdev commented on src/Clients/CaradhrasCardClient.php
> +            'id_tipo_plastico' => config('app.plastic_id'),
Huuum temos esse plastic_id em algum lugar?

2023-01-12 13:44 UTC, arthurtavaresdev commented on src/Clients/CaradhrasCardClient.php
> +        $this->setCardPassword($cardId, random_int(1000, 9999));
Mude isso na assinatura do método talvez

2023-01-12 13:44 UTC, arthurtavaresdev commented on src/Clients/CaradhrasCardClient.php
> +    public const CARD_NOT_PRINTED = 'Invalid card status for activation.';
Então a remova.

2023-01-12 13:44 UTC, arthurtavaresdev commented on src/Clients/CaradhrasCardClient.php
> +                403 => trans(self::CARD_NOT_PRINTED),
Nesse caso é constant. Vai ser "hardcode" de qualquer forma

2023-01-12 14:32 UTC, davi0kaipper commented on src/Clients/CaradhrasCardClient.php
> +            'id_tipo_plastico' => config('app.plastic_id'),
não tinha. e na real tem altos config nesse pacote que tão solto sem os arquivos de referência. vou providenciar

2023-01-18 13:56 UTC, arthurtavaresdev requested changes

2023-01-18 13:56 UTC, arthurtavaresdev commented on src/Clients/CaradhrasCardClient.php
> +            ->withHeaders(['senha' => str_pad(random_int(1000, 9999), 4, '0', STR_PAD_LEFT)])
Acredito que não devemos ter essa lógica de senha gerado aleatoriamente dentro do pacote, isso deve ser alterado na chamada desse método dessa API e lá sim aleatorizar esta senha

```suggestion
    public function setCardPassword(string $cardId, $password): object
    {
        return $this->apiClient()
            ->withHeaders(['senha' => str_pad($password, 4, '0', STR_PAD_LEFT)])
```

2023-01-18 13:56 UTC, arthurtavaresdev commented on src/Clients/CaradhrasCardClient.php
> +            'dataValidade' => now()->addYears(5)->format('Y-m-d\TH:i:s'),
Eu sei que pedi pra mudar isso, mas a pouco descobri que o Carbon tem uma implementação feita para este padrão, prefiro utiliza-la

```suggestion
            'dataValidade' => now()->addYears(5)->toIso8601String
```

2023-01-18 13:56 UTC, arthurtavaresdev commented on src/Clients/CaradhrasMainClient.php
> +            'amount' => $amount * 100,
Me incomoda, essa simplificação do Money pattern. Mas deixa

2023-01-18 13:56 UTC, arthurtavaresdev commented on src/Clients/CaradhrasMainClient.php
> +        }
Não quer separar esses itens relacionados a recarga de telefone em +1 cliente? 😅

2023-01-20 17:35 UTC, davi0kaipper commented on src/Clients/CaradhrasCardClient.php
> +            ->withHeaders(['senha' => str_pad(random_int(1000, 9999), 4, '0', STR_PAD_LEFT)])
pode crer. entendi agora

2023-01-24 13:59 UTC, arthurtavaresdev approved these changes
LGTM

Só dar uma olhadinha nos testes

2023-02-02 16:43 UTC, merged