Funcionalidade: para cancelar Alias Banks
idezdigital/laravel-caradhras-sdk pull request #30
Opened 2023-08-24 22:23 UTC by albuquerque53

## :mag: Descrição do PR

Foram adicionados dois métodos:
1. `list`: Para fazer uma listagem dos Alias associados a determinada conta.
2. `delete`: Para cancelar determinado Alias.

A idéia é adicionarmos a possibilidade de listar e cancelarmos aliases através desse SDK.

## 🏷️  Ticket

- https://app.clickup.com/t/8678kz73m

## 📃 Documentação

- [List alias account](https://lighthouse.dock.tech/docs/cards-and-digital-banking-api-reference/ed4f4276b1ede-list-alias-account)
- [Delete alias account](https://lighthouse.dock.tech/docs/cards-and-digital-banking-api-reference/5fb6422ea6c39-delete-alias-account)

2023-09-05 21:03 UTC, rafaellaurindo requested changes
Belo trabalho! Adicionei uns questionamentos principalmente à respeito da tratativa de erros.

2023-09-05 21:03 UTC, rafaellaurindo commented on tests/Unit/Clients/CaradhrasAliasClientTest.php
> +        );
Poderíamos usar _arrow-function_ aqui.

2023-09-05 21:03 UTC, rafaellaurindo commented on tests/Unit/Clients/CaradhrasAliasClientTest.php
> +                return $request->url() === $expectedRequestUrl &&
Podemos validar o método http tbm?

2023-09-05 21:03 UTC, rafaellaurindo commented on tests/Unit/Clients/CaradhrasAliasClientTest.php
> +                return $request->url() === $expectedRequestUrl &&
Seria interessante validar tbm o método HTTP.

2023-09-06 11:09 UTC, albuquerque53 commented on src/Clients/CaradhrasAliasClient.php
> +            ->apiClient(false)
Você tá certo men, mosquei aqui

2023-09-06 11:12 UTC, albuquerque53 commented on tests/Unit/Clients/CaradhrasAliasClientTest.php
> +        );
Valeu pelo toque

2023-09-06 20:23 UTC, rafaellaurindo approved these changes
LGTM!

2023-09-06 20:23 UTC, rafaellaurindo commented on src/Clients/CaradhrasAliasClient.php
> +    public function delete(int $accountId, AliasBankProvider $bankProvider): Response
Não é uma prática muito comum retornarmos o objeto `Response`, o que de retornar apenas o conteúdo da resposta?

```php
return $response->object();
```

2023-09-14 16:34 UTC, albuquerque53 commented on src/Clients/CaradhrasAliasClient.php
> +    public function delete(int $accountId, AliasBankProvider $bankProvider): Response
Concordo meu chapa

2023-09-14 16:36 UTC, merged