Hotfix: nullable return
idezdigital/laravel-caradhras-sdk pull request #42
Opened 2024-02-20 14:42 UTC by LucasWPL

A rota `/v1/reports/{account}` da API _declarables_ pode retornar um 204, que quando tenta transformar em objeto retorna _null_

![image](https://github.com/idezdigital/laravel-caradhras-sdk/assets/65680775/828968e3-2350-456b-acf5-bfb6f64953ba)

2024-02-20 14:44 UTC, LucasWPL commented
O ajuste na formatação foi o próprio gitlab que fez :eyes:

2024-02-20 15:04 UTC, rafaellaurindo requested changes
Precisamos ajustar a API pra tratar o caso `null`, senão pode continuar quebrando, agora em outra etapa.

2024-02-20 15:04 UTC, rafaellaurindo commented on src/Clients/CaradhrasIncomeReportsClient.php
> +    public function getAvailable(int $accountId): ?object
Acho que só retornar `null` pode causar erros na tratativa da API

2024-02-21 13:43 UTC, rafaellaurindo approved these changes

2024-02-21 13:44 UTC, merged